### ISSUE TITLE
Bug when outputting redshifts between 0 and 1

### ISSUE THREAD

**Issue by GabrieleParimbelli** [miknab/EuclidEmulator2#5] opened 2020-11-04 10:19 UTC
Hi, I found a bug (probably a rounding error?) when asking the non-linear corrections at redshifts in the [0,1] interval. No matter which value you ask, the output looks exactly the same for all of them (i.e. the one at z=0).

**Comment by miknab** [comment] 2020-11-04 16:10
Hi Gabriele,

Thanks a lot for your feedback. 

Can I ask you for some more details, please? What method of feeding the input parameters to EE2 did you use?

Cheers, Mischa

**Comment by GabrieleParimbelli** [comment] 2020-11-04 16:26
So, I ran the file "./tests/run_test.sh" that executes the emulator 4 times.
- In the first run, all the columns corresponding to redshifts between 0 and 1 are exactly the same.
- I the run that calls the "from_ee2_parfile" parameter file, I added more redshifts between 0 and 1 and the results were always the same.
- For the 3rd and the 4th run, I modified the CAMB and Class parameter files asking a redshift between 0 and 1: once again, the output was the same as when z=0 was asked.

Thanks,
Gabri

**Comment by GabrieleParimbelli** [comment] 2020-11-05 11:26
Hi, I installed the emulator on the cluster of my institution and it turned out to work fine, while still on my laptop the problem still exists.
For completeness my machine runs Operating System: Ubuntu 16.04.7 LTS, Kernel: Linux 4.15.0-122-generic, Architecture: x86-64, if anyone else has the same issue

**Comment by miknab** [comment] 2020-11-08 10:46
Thanks for this update. In this case it's going to be tough to figure out where the problem is as I don't have access to a machine running ubuntu. I will see what I can do...

Please keep me posted in case you find out what the problem is.

**Comment by GabrieleParimbelli** [comment] 2021-02-16 13:57
Hello Mischa, 
I changed my PC and the issue has disappeared. I don't have a clue why that happened only on my old one, probably as you said it was just a rounding error in the libraries.
I don't know if you want to close this issue as I was the only one that had this problem.
Thanks!

**Comment by miknab** [comment] 2021-09-05 12:18
Hi Gabriele, sorry for an answer that is several months late. Yes, I'll close the issue then. Thank you...

**Closed as completed by miknab** 2021-09-05 12:18 UTC
